# Site settings
title: Comment venir au laboratoire de mathématiques Paul Painlevé de Lille
email: kroum.tzanev@math.univ-lille1.fr
url: "https://ktzanev.github.io" # the base hostname & protocol for your site
github:
  user : ktzanev
  branch: gh-pages
baseurl: "/venir-labopp/" # the subpath of your site, e.g. /blog/
address: > #   L'adresse du laboratoire
  bâtiment M2<br>
  Cité Scientifique<br>
  59650 Villeneuve-d'Ascq
gps: ["50.609","3.138"]

# libraries
revealjsurl: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.2.0/" # the path to RevealJS
jqueryurl: "https://code.jquery.com/" # the path to jQuery
bootstrapurl: "https://netdna.bootstrapcdn.com/bootstrap/3.1.1/" # the path to Bootstrap
highlightjsurl: "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/" # the path to Bootstrap

# Build settings
permalink: pretty
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: true
  auto_ids: false

gems:
  - jemoji

exclude:
  - Work
